apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-configmap-reload
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kubernetes-configmap-reload
    spec:
      containers:
      - image: "{{ image_id }}"
        name: kubernetes-configmap-reload
        ports:
        - containerPort: 8080
          name: http

