apiVersion: v1
kind: Service
metadata:
  name: kubernetes-configmap-reload
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nginx.nginxmydomain.tk.
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: http
    targetPort: 80
  selector:
    app: nginx

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-configmap-reload
spec:
  template:
    metadata:
      labels:
        app: kubernetes-configmap-reload
    spec:
      containers:
      - image: naresh240/kubernetes-configmap-reload:latest
        name: kubernetes-configmap-reload
        ports:
        - containerPort: 8080
          name: http
