- hosts: localhost
  gather_facts: no
  tasks:
  - name: Deploy the service
    command: "kubectl apply -f service.yml"
    delegate_to: localhost
  - name: Deploy the application
    command: "kubectl apply -f deployment.yml"
    delegate_to: localhost
