- hosts: localhost
  tasks:
  - name: Deploy the service
    k8s:
      state: present
      definition: "{{ lookup('template', 'kubernetes-configmap.yml') | from_yaml }}"
      validate_certs: no
      namespace: default
