- hosts: localhost
  gather_facts: no
  tasks:
  - name: Deploy the service
    command: "kubectl apply -f service.yml"
    delegate_to: localhost
    ignore_errors: yes
    namespace: default
  - name: Deploy the application
    command: "kubectl install deployment.yml"
    delegate_to: localhost
    ignore_errors: yes
